version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: development
    open-pull-requests-limit: 25
    groups:
      pip-minor-deps:
        update-types:
          - "minor"
          - "patch"
      pip-major-deps:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: development
    open-pull-requests-limit: 25
    groups:
      gh-minor-deps:
        update-types:
          - "minor"
          - "patch"
      gh-major-deps:
        update-types:
          - "major"