# MAIN DATA -------------------------------------------------------------------
# Site data
site_name: Data-Lunch
site_url: "http://Michele-Alberti.github.io/data-lunch/"
site_author: Michele Alberti

# Repository
repo_name: Michele-Alberti/data-lunch
repo_url: https://github.com/Michele-Alberti/data-lunch
edit_uri: ""

# Navigation bar
nav:
- About Us: index.md
- getting_started.md
- Documentation: reference/

# THEME -----------------------------------------------------------------------
# Theme
theme:
  name: "material"
  logo: assets/logo-dark.png
  favicon: assets/favicon.ico
  palette:
    # Light mode
    - scheme: dlunch
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow

# Custom colors
extra_css:
  - stylesheets/extra.css

# PLUGINS AND MARKDOWN EXTENSIONS ---------------------------------------------
# Docs versioning (mike)
extra:
  version:
    provider: mike
    default: stable
    alias: true

# Plugins
plugins:
- search
- autorefs
- gh-admonitions
- gen-files:
    scripts:
    - scripts/docs/generate_reference_pages.py
    - scripts/docs/generate_getting_started.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://omegaconf.readthedocs.io/en/latest/objects.inv
        - https://passlib.readthedocs.io/en/stable/objects.inv
        - https://pandas.pydata.org/docs/objects.inv
        - https://param.holoviz.org/objects.inv
        - https://docs.sqlalchemy.org/objects.inv
        options:
          heading_level: 3
          show_if_no_docstring: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          summary: true
          docstring_options:
            returns_named_value: false
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg