site_name: Data-Lunch
site_url: "http://Michele-Alberti.github.io/data-lunch/"

theme:
  name: "material"
  logo: assets/logo-dark.png
  favicon: assets/favicon.ico
  palette:
    scheme: dlunch
  extra:
    version:
      provider: mike
      default: stable
      alias: true

extra_css:
  - stylesheets/extra.css

nav:
- Getting Started: getting_started.md
- Code Reference: reference/

plugins:
- gh-admonitions
- search
- autorefs
- gen-files:
    scripts:
    - scripts/docs/generate_reference_pages.py
    - scripts/docs/generate_getting_started.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://omegaconf.readthedocs.io/en/latest/objects.inv
        - https://passlib.readthedocs.io/en/stable/objects.inv
        - https://pandas.pydata.org/docs/objects.inv
        - https://param.holoviz.org/objects.inv
        - https://docs.sqlalchemy.org/objects.inv
        options:
          heading_level: 3
          show_if_no_docstring: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          summary: true
          docstring_options:
            returns_named_value: false
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences