# Server config are used with instantiate
_target_: builtins.dict
_convert_: all
address: 0.0.0.0
port: ${oc.decode:${oc.env:PORT, 5000}}
websocket_origin: "*"
xheaders: true
verbose: false
open: false
static_dirs:
  images: ./data_lunch_app/static/images
  css: ./data_lunch_app/static/css
compress_response: true
cookie_secret: ${oc.env:DATA_LUNCH_COOKIE_SECRET} # Secure cookies are required (this vakue can't be null)
enable_xsrf_cookies: true