address: 0.0.0.0
port: ${oc.decode:${oc.env:PORT, 5000}}
websocket_origin: "*"
xheaders: true
verbose: false
open: false
static_dirs:
  images: ./data_lunch_app/static/images
  css: ./data_lunch_app/static/css
compress_response: true
cookie_secret: ${oc.env:DATA_LUNCH_COOKIE_SECRET}
oauth_expiry: 15
oauth_encryption_key: ${oc.env:DATA_LUNCH_OAUTH_ENC_KEY}
enable_xsrf_cookies: true