# FOR THE RUNTIME IMAGE:
# alpine 3.16 with python 3.10.8
# See makefile for docker commands

# PYTHON 3.10.8
FROM python:3.11.4-slim-bookworm

# Tell the docker runtime process to use the default shell
SHELL ["/bin/sh", "-c"]

# Install tesseract
RUN apt update && apt install -y \
  apt-transport-https \
  lsb-release \
  sqlite3 \
  libsqlite3-dev \
  dnsutils \
  gcc \
  libpq-dev \
  && echo "deb https://notesalexp.org/tesseract-ocr5/$(lsb_release -cs)/ $(lsb_release -cs) main" \
  | tee /etc/apt/sources.list.d/notesalexp.list > /dev/null \
  && apt update -oAcquire::AllowInsecureRepositories=true \
  && apt install -y notesalexp-keyring -oAcquire::AllowInsecureRepositories=true --allow-unauthenticated \
  && apt update && apt install -y \
  tesseract-ocr \
  tesseract-ocr-ita \
  && apt-get clean all && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements/requirements.txt /app/requirements/requirements.txt

RUN python3 -m pip install --no-cache-dir -r /app/requirements/requirements.txt

# Copy data
WORKDIR /app
COPY . .

#Inistall command line tool
RUN pip install --no-cache-dir -e .

# Add environment variables
ENV PANEL_APP=data-lunch-app

# Expose port 5000
EXPOSE 5000

# Set command
ENTRYPOINT ["python", "-m", "data_lunch_app"]