# oauth config (not used by panel.serve)
oauth_encryption_key: ${oc.env:DATA_LUNCH_OAUTH_ENC_KEY}
oauth_expiry: 15
# Template not set by panel.serve
auth_error_template: data_lunch_app/templates/error.html
# Autorization callback (_partial_ is required for usage with lambda functions)
authorization_callback:
  _target_: data_lunch_app.auth.authorize
  _partial_: True
  # Flag to authorize access of guest users to the home page
  # They can only place orders for guests 
  authorize_guest_users: true
# Set cookie function arguments (set to empty dict to turn off)
cookie_kwargs:
  httponly: true
  secure: true
  samesite: strict

# BASIC AUTHENTICATION DATA
basic_auth:
  # Those values are  used by basic authentication specific features
  # PASSWORD (used only if basic auth is active)
  # Special charachters and reg expression used to check (or create) a password
  psw_special_chars: ';:,.+-=_#!$%&?^*@'
  psw_regex: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[${auth.basic_auth.psw_special_chars}]).{8,}$
  # Set generated password length (call to generate_password)
  generated_psw_length: 12
  # GUEST USER (used only if basic auth is active)
  # If true create default guest user credentials (i.e. a user named "guest")
  # It is an unprivileged user (is_guest = true) named guest
  guest_user: true
  # Guest user password flag default value
  # If true a new password for guest user is set everytime the main function is called
  default_reset_guest_user_password_flag: false