version: "3.9"
services:
  web:
    image: michelealberti/data-lunch-app:${IMAGE_VERSION}
#    build:
#      context: .
#      dockerfile: ./docker/web/Dockerfile.web
    volumes:
      - ./shared_data:/app/shared_data
    expose:
      - ${PORT} # Expose port from env variable to an ephemeral port (used by load balancer)
    environment:
      PANEL_APP: ${PANEL_APP}
      PANEL_ENV: ${PANEL_ENV}
      GCLOUD_PROJECT: ${GCLOUD_PROJECT}
      GCLOUD_BUCKET: ${GCLOUD_BUCKET}
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      PORT: ${PORT}
      DATA_LUNCH_COOKIE_SECRET: ${DATA_LUNCH_COOKIE_SECRET}
      DATA_LUNCH_OAUTH_ENC_KEY: ${DATA_LUNCH_OAUTH_ENC_KEY}
      DATA_LUNCH_OAUTH_KEY: ${DATA_LUNCH_OAUTH_KEY}
      DATA_LUNCH_OAUTH_SECRET: ${DATA_LUNCH_OAUTH_SECRET}
      DATA_LUNCH_OAUTH_REDIRECT_URI: ${DATA_LUNCH_OAUTH_REDIRECT_URI}
    command: ${PANEL_ARGS}
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/template.conf:/etc/nginx/template.conf:ro
      - ./ssl/www:/var/www/certbot/:ro
      - ./ssl/conf/:/etc/letsencrypt/:rw
    depends_on:
      - web
    environment:
      DOMAIN: ${DOMAIN}
      PORT: ${PORT}
    ports:
      - "443:443" # port 443 available on localhost
      - "80:80" # port 80 available on localhost
    command: /bin/bash -c "echo 'selected domain $DOMAIN - selected port $PORT' && envsubst '$$DOMAIN $$PORT' < /etc/nginx/template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./ssl/www/:/var/www/certbot/:rw
      - ./ssl/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    environment:
      DOMAIN: ${DOMAIN}
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${CERT_EMAIL} --agree-tos --no-eff-email
      -d ${DOMAIN}
networks:
  default:
    driver: bridge
    name: data-lunch
