shared_data_folder: ${oc.env:PANEL_SHARED_DATA_FOLDER, /app/shared_data}
name: lunch
db_path: ${db.shared_data_folder}/${db.name}.db
url: sqlite:///${db.db_path}
engine:
  _target_: sqlalchemy.create_engine
  url: ${db.url}
menu_table: menu
# SAVE DATABASE TO CLOUD STORAGE
ext_storage_upload:
    enabled: true # Set to false to turn off database upload completely
    source_file_name: ${db.db_path}
    destination_blob_name: ${db.name}.db
    bucket_name: ${oc.env:GCLOUD_BUCKET, not_defined}
    project: ${oc.env:GCLOUD_PROJECT, not_defined}