shared_data_folder: ${oc.env:PANEL_SHARED_DATA_FOLDER, /tmp/shared_data}
name: lunch
db_path: ${db.shared_data_folder}/${db.name}.db
url: sqlite:///${db.db_path}
engine:
  _target_: sqlalchemy.create_engine
  url: ${db.url}
menu_table: menu
orders_query: "
  SELECT o.id, o.user, o.lunch_time, m.item
  FROM orders o
  LEFT JOIN menu m
  ON m.id = o.menu_item_id ;
  "
# GOOGLE CLOUD
gcloud_project: ${oc.env:GCLOUD_PROJECT, not_defined}
gcloud_bucket: mic-datalunch-p-csb-usea1-web-jxk8
# STORAGE DB FILE IN BUCKET
gcloud_storage: # Set to null to turn off database download from bucket
  upload:
    _target_: data_lunch_app.cloud.upload_to_gcloud
    source_file_name: ${db.db_path}
    destination_blob_name: ${db.name}.db
    bucket_name: ${db.gcloud_bucket}
    project: ${db.gcloud_project}
  download:
    _target_: data_lunch_app.cloud.download_from_gcloud
    source_blob_name: ${db.name}.db
    destination_file_name: ${db.db_path}
    bucket_name: ${db.gcloud_bucket}
    project: ${db.gcloud_project}