defaults:
  - _self_ #configs from the Defaults List are overriding config.yaml
  - gui: default
#  - _self_ #config.yaml is overriding configs from the Defaults List

# APP
file_name: menu_file
export_file_name: lunch_order.xlsx
nthreads: null

# OPTIONS
# Dashboard options
result_column_text: "# Orders"
time_column_text: "#### Summary"
lunch_times_options:
  - "12:00"
  - "12:30"
  - "13:00"
  - "13:30"
  - "14:00"
  - "14:30"
menu_items_to_concat:
  - Insalatona Primavera
  - Insalatona Valtellina
  - Insalatona Sorrento
  - Insalatona Chicken Salad
  - Insalatona Esplosiva
  - Insalatona Follie
  - Macedonia
  - Dolce
  - Caffé
  - Altro
salad_list: |
  🌱 <strong>Primavera:</strong> 🥬 + <i>pomodorini, mozzarella, carciofi, funghi, olive.</i> <br>
  ⛰️ <strong>Valtellina:</strong> 🥬 + <i>rucola, pomodorini, bresaola, grana.</i> <br>
  🍋 <strong>Sorrento:</strong> 🥬 + <i>pomodorini, bufala, olive, noci, carciofi.</i> <br>
  🍗 <strong>Chicken Salad:</strong> 🥬 + <i>pomodorini, mozzarella, mais, pollo.</i> <br>
  🧨 <strong>Esplosiva:</strong> 🥬 + <i>pomodorini, tonno, fagioli, cipolle.</i> <br>
  🤪 <strong>Follie:</strong> 🥬 + <i>pomodori secchi, melanzane, tonno, acciughe.</i> <br>

# Notifications
notifications:
  duration: 0
# Drop unused menus entries in orders tables (drop unused if true)
drop_unused_menu_items: true

# QUERIES
# Orders
orders_query: |-
  SELECT o.user, o.lunch_time, m.item
  FROM orders o
  LEFT JOIN menu m
  ON m.id = o.menu_item_id;
# Stats
stats_query: |-
  SELECT STRFTIME('%Y', id) AS "Year", 
    STRFTIME('%m', id) AS "Month", 
    (SUM(hungry_people) - SUM(hungry_guests)) AS "Starving Locals",
    SUM(hungry_guests) AS "Ravenous Guests",
    SUM(hungry_people) AS "Hungry People"
  FROM stats
  GROUP BY "Year", "Month"
  ORDER BY "Year", "Month";
stats_id_cols:
  - year
  - month

# SERVER SCHEDULED ACTIVITIES
scheduled_tasks: # Set to [] empty list to turn it off
  # CLEANING
  scheduled_cleaning: null
#    name: scheduled cleaning
#    hour: 15
#    minute: 0
#    period: 1d