defaults:
  - _self_ #configs from the Defaults List are overriding config.yaml
  - gui: default
#  - _self_ #config.yaml is overriding configs from the Defaults List

# APP
file_name: menu_file
export_file_name: lunch_order.xlsx
nthreads: null

# OPTIONS
# Dashboard options
result_column_text: "# Orders"
time_column_text: "#### Summary"
lunch_times_options:
  - "12:00"
  - "12:30"
  - "13:00"
  - "13:30"
  - "14:00"
  - "14:30"
menu_items_to_concat:
  - Insalatona Primavera
  - Insalatona Valtellina
  - Insalatona Sorrento
  - Insalatona Chicken Salad
  - Insalatona Esplosiva
  - Insalatona Follie
  - Dolce
  - Caffé
  - Altro
salad_list: |
  🌱 <strong>Primavera:</strong> 🥬 + <i>pomodorini, mozzarella, carciofi, funghi, olive.</i> <br>
  ⛰️ <strong>Valtellina:</strong> 🥬 + <i>rucola, pomodorini, bresaola, grana.</i> <br>
  🍋 <strong>Sorrento:</strong> 🥬 + <i>pomodorini, bufala, olive, noci, carciofi.</i> <br>
  🍗 <strong>Chicken Salad:</strong> 🥬 + <i>pomodorini, mozzarella, mais, pollo.</i> <br>
  🧨 <strong>Esplosiva:</strong> 🥬 + <i>pomodorini, tonno, fagioli, cipolle.</i> <br>
  🤪 <strong>Follie:</strong> 🥬 + <i>pomodori secchi, melanzane, tonno, acciughe.</i> <br>
guest_types: # Check also guests icons in panel/gui
  - Edison Guest
  - External Guest

# Notifications
notifications:
  duration: 0
# Drop unused menus entries in orders tables (drop unused if true)
drop_unused_menu_items: true

# STATISTICS DATAFRAMES
stats_id_cols:
  - Year
  - Month
stats_locals_column_name: Officine MI # Non-guest users (used to fill NaNs)

# SERVER SCHEDULED ACTIVITIES
scheduled_tasks: # Set to [] empty list to turn it off
  - kwargs:
      name: reset guest password
      enabled: false
      hour: null
      minute: null
      period: 1d
    callable:
      _target_: data_lunch_app.scheduled_tasks.reset_guest_user_password
  - kwargs:
      name: scheduled cleaning
      enabled: true
      hour: 04
      minute: 00
      period: 1d
    callable:
      _target_: data_lunch_app.scheduled_tasks.clean_files_db
  - kwargs:
      name: database upload
      enabled: ${db.ext_storage_upload.enabled}
      hour: 11
      minute: 25
      period: 60min
    callable:
      _target_: data_lunch_app.scheduled_tasks.upload_db_to_gcp_storage
      source_file_name: ${db.ext_storage_upload.source_file_name}
      destination_blob_name: ${db.ext_storage_upload.destination_blob_name}
      bucket_name: ${db.ext_storage_upload.bucket_name}
      project: ${db.ext_storage_upload.project}

