# Bump version with Commitizen

name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    name: Bump version and log
    outputs:
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@0.15.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
  merge_back_to_dev:
    needs: bump_version
    runs-on: ubuntu-latest
    name: Merge back to dev
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          ref: main
      - name: Set Git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: Merge master back to dev
        run: |
          git checkout development
          git merge --no-ff main -m "Merge branch 'main' into development"
          git push
